# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 570ade69b20e7556a959e627910b360a8513e9184be2d92a0abdcc2e762f5ca16874b6dac33f49403dab3313037bb928dc25b073f875d918dc431f1612cf6342

test:
  secret_key_base: ca1c58873921d0962e328b4786618fb7600f199452e529f04e7de9abfb498348b91802c8c5ff21af0b69268ce24475f5db29dddc829c1e02fd279501dd646121

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
